/*
    Create a hecking simulator which has green background and it shows these messages with random delay of 1 to 7 seconds

    Initializing Hacking...
    Reading your files...
    password files Detected...
    Sending all passwords and personal files to server...
    Cleaning up...

    The three dot must blink so that it looks like a terminal

*/